name: 'OpenWrt ImageBuilder Github Action'
description: 'Build OpenWrt custom images using ImageBuilder - https://openwrt.org/docs/guide-user/additional-software/imagebuilder '
inputs:
  profile: 
    description: 'Specifies the target image to build - PROFILE'
    required: true
    default: 'bcm27xx-bcm2711'
  openwrt-version:
    description: 'OpenWrt version'
    required: true
    default: 'master'
  packages:
    description: 'A list of packages to embed into the image - PACKAGES'
    required: false
    default: ''
  files:
    description: 'Directory with custom files to include - FILES'
    required: false
    default: 'files'
  disabled-services:
    description: 'The names of services from /etc/init.d to disable, e.g. dhcp for dnsmasq - DISABLED_SERVICES'
    required: false
    default: ''
  bin-dir:
    description: 'Alternative output directory for the images - BIN_DIR'
    required: false
    default: 'bin'
  extra-image-name:
    description: 'Add this to the output image filename (sanitized) - EXTRA_IMAGE_NAME'
    required: false
    default: ''
  debug:
    description: 'Set to "1" to enable additional debug info like the content of .config'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - run: |
        mkdir bin && chmod 777 bin && \
        docker run --rm \
          -v ${{ github.action_path }}/make_image.sh:/home/build/openwrt/github_make_image.sh \
          -v "$(pwd)"/${{ inputs.files }}/:/home/build/openwrt/files \
          -v "$(pwd)"/${{ inputs.bin-dir }}/:/home/build/openwrt/bin:rw \
          -e PACKAGES="${{ inputs.packages }}" \
          -e DISABLED_SERVICES="${{ inputs.disabled-services }}" \
          -e FILES="files" \
          -e EXTRA_IMAGE_NAME="${{ inputs.extra-image-name }}" \
          -e DEBUG="${{ inputs.debug }}" \
          openwrtorg/imagebuilder:${{ inputs.profile }}-${{ inputs.openwrt-version }} \
            /home/build/openwrt/github_make_image.sh
      shell: bash

